Init version for Centec E582-48X6Q platform
The E582-48X6Q use Centec Networks GoldenGate (CTC8096) as switch
ASIC.E582-48X6Q have 48x10G SFP+ and 6x40G QSFP ports.CPU module is
Intel Xeon D-1548.

Change-Id: I01b5796d14063d8dded749b72518089f77d8acc7

diff --git a/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in b/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
--- a/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
+++ b/yocto/openswitch/meta-distro-openswitch/recipes-onie/onie-installer/files/onie-installer.in
@@ -274,11 +274,22 @@ populate_rootfs()
            -e "s/OPENSWITCH_CONFIG_CONSOLE/${CONFIG_CONSOLE}/g" \
            -e "s/OPENSWITCH_COMMANDLINE_APPEND/${COMMANDLINE_APPEND}/g" \
        ${mount_point}/boot/grub/grub.cfg
-    ${mount_point}/usr/sbin/grub-install --force --boot-directory ${mount_point}/boot --recheck ${NOS_DISK} || {
-        echo -e "${red}ERROR${normal}: Failed to install the $label GRUB!"
+
+    if [ "$install_firmware" = "uefi" ] ; then
+        ${mount_point}/usr/sbin/grub-install --force --efi-directory="/boot/efi" --boot-directory=${mount_point}/boot --recheck ${NOS_DISK} > /dev/null 2>&1 || {
+            echo -e "${red}ERROR${normal}: Failed to install the $label GRUB!"
+            exit 1
+        }
+    elif [ "$install_firmware" = "bios" ] ; then
+        ${mount_point}/usr/sbin/grub-install --force --boot-directory ${mount_point}/boot --recheck ${NOS_DISK} > /dev/null 2>&1 || {
+            echo -e "${red}ERROR${normal}: Failed to install the $label GRUB!"
+            exit 1
+        }
+        chattr +i ${mount_point}/boot/grub/i386-pc/core.img
+    else
+        echo -e "${red}ERROR${normal}: Unsupported firmware type! Aborting"
         exit 1
-    }
-    chattr +i ${mount_point}/boot/grub/i386-pc/core.img
+    fi
 
     # Update the grub environment
     if ! $INSTALLING_FROM_OPS ; then
@@ -335,6 +346,19 @@ else
 
     INSTALLING_FROM_OPS=true
     config_mount_point=/var/local
+fi
+
+# For the diffierent type of firmware (bios/uefi), we need to perform differently grub-install method.
+# For UEFI system, we should define FIRMWARE_TYPE=uefi in onie.config file. And for bios system, don't
+# need to do anything.
+install_firmware=bios
+# Here perform a few sanity chcek
+if [ "$FIRMWARE_TYPE" = "uefi" ] ; then
+    [ -d "/sys/firmware/efi/efivars" ] || {
+          echo -e "${red}ERROR${normal}: This machine does not support UEFI. Aborting"
+          exit 1
+    }
+    install_firmware="uefi"
 fi
 
 banner() {
